link2aleph:
  image: moravianlibrary/link2aleph
  volumes:
    - /data/link2aleph/:/data
  ports:
    - "80:5000"
  environment:
    - "TZ=Europe/Prague"
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always

